### ISSUE TITLE
Won't allow homebridge to run

### ISSUE THREAD

**Issue by jbf000** [normen/homebridge-landroid#26]
I am new to homebridge installed the plugin in windows and it wont allow homebridge to start

Below are the error messages:-

TypeError: Cannot read property 'server' of undefined
    at new Worx (C:\Users\jeff\AppData\Roaming\npm\node_modules\homebridge-landroid\node_modules\iobroker.worx\lib\api.js:155:38)
    at HomebridgeAPI.<anonymous> (C:\Users\jeff\AppData\Roaming\npm\node_modules\homebridge-landroid\index.js:36:26)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (C:\Users\jeff\AppData\Roaming\npm\node_modules\homebridge\src\api.ts:251:10)
    at Server.start (C:\Users\jeff\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:160:14)
    at cli (C:\Users\jeff\AppData\Roaming\npm\node_modules\homebridge\src\cli.ts:80:10)
    at Object.<anonymous> (C:\Users\jeff\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

What am i doing wrong ?

Cheers Jeff

**Comment by Schosch83** [comment]
I have the same problem.
TypeError: Cannot read property 'server' of undefined
    at new Worx (/usr/lib/node_modules/homebridge-landroid/node_modules/iobroker.worx/lib/api.js:155:38)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-landroid/index.js:36:26)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:160:14)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

This Issue is coming after a new installation of homebridge. before was working
And this is coming on installation homebridge-landroid:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

**Comment by Baxtar** [comment]
Hi I have the same Problem.
Same problem on 2 systems....raspberrypi 4 with Homebridge and raspberrypi 4 with HOOBS. As soon as I install the plug-in, the homebridge crasps and Hobbs can no longer be started. After uninstalling, everything goes back to normal.

**Comment by normen** [comment]
I guess the ioborker library that this plugin uses has changed something, gotta investigate

**Comment by normen** [comment]
In homebridge-landroid 0.9.1 I downgraded the library to 1.0.2 which works fine just as before.
