### ISSUE TITLE
Error: unsupported

### ISSUE THREAD

**Issue by iuliusmaximilian** [normen/homebridge-landroid#42]
Hi, I receive this issue. It's is more or less a standard homebridge installation on my Rasp. 4 with latest upgrades and node v17.9.0.
```
[15.8.2022, 20:25:39] [homebridge-landroid] Restarting Process...
[15.8.2022, 20:25:41] [homebridge-landroid] Launched child bridge with PID 2248
[8/15/2022, 8:25:42 PM] Registering platform 'homebridge-landroid.Landroid'
[15.8.2022, 20:25:42] [homebridge-landroid] Loaded homebridge-landroid v0.9.6 child bridge successfully
[8/15/2022, 8:25:42 PM] Loaded 1 cached accessories from cachedAccessories.0EC3A48DE075.
[8/15/2022, 8:25:42 PM] [homebridge-landroid] Restoring Landroid Landroid Plus from HomeKit
[8/15/2022, 8:25:42 PM] [homebridge-landroid] Fallback for On/Off switch
[8/15/2022, 8:25:42 PM] [homebridge-landroid] DidFinishLaunching
[8/15/2022, 8:25:42 PM] [homebridge-landroid] worx is selected
[8/15/2022, 8:25:42 PM] Homebridge v1.5.0 (HAP v0.10.2) (homebridge-landroid) is running on port 38710.
[8/15/2022, 8:25:43 PM] [homebridge-landroid] Connected to WORX cloud.
[8/15/2022, 8:25:44 PM] [homebridge-landroid] Found Landroid in Worx Cloud with name: XXX
[8/15/2022, 8:25:44 PM] [homebridge-landroid] Error: unsupported
    at configSecureContext (node:internal/tls/secure-context:280:15)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Object.connect (node:_tls_wrap:1623:48)
    at Object.buildBuilder (/usr/lib/node_modules/homebridge-landroid/node_modules/mqtt/lib/connect/tls.js:20:26)
    at MqttClient.wrapper [as streamBuilder] (/usr/lib/node_modules/homebridge-landroid/node_modules/mqtt/lib/connect/index.js:155:36)
    at MqttClient._setupStream (/usr/lib/node_modules/homebridge-landroid/node_modules/mqtt/lib/client.js:415:22)
    at new MqttClient (/usr/lib/node_modules/homebridge-landroid/node_modules/mqtt/lib/client.js:395:8)
    at Object.connect (/usr/lib/node_modules/homebridge-landroid/node_modules/mqtt/lib/connect/index.js:157:18)
    at Worx._connectMqtt (/usr/lib/node_modules/homebridge-landroid/node_modules/iobroker.worx/lib/api.js:245:27)
    at /usr/lib/node_modules/homebridge-landroid/node_modules/iobroker.worx/lib/api.js:212:34
```

**Comment by normen** [comment]
Looks similar to #40

**Comment by iuliusmaximilian** [comment]
Don’t think so because of much newer node version ?

**Comment by normen** [comment]
Its basically the same issue, an OS-level TLS incompatibility.

Maybe try this: https://nodejs.org/docs/latest-v17.x/api/cli.html#--openssl-legacy-provider

Don't know how to get that parameter through to the nodejs instance that homebridge is running though, guess theres some parameter in the homebridge executable for that.

**Comment by normen** [comment]
I also pushed an update `0.9.7` with the latest worx libraries in case they fixed this issue.

**Comment by iuliusmaximilian** [comment]
![2B1732E1-7CA8-41E0-AFD8-92699EC22CAD](https://user-images.githubusercontent.com/28545473/187022444-f7ed261e-21f3-44a1-9b94-c90ebc0277db.png)

**Comment by normen** [comment]
Yeah, well. As the stack trace clearly states the issue is internal to node. It seems to work for most people including me. Google `node tls unsupported` or something along those lines.
