### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-landroid

### ISSUE THREAD

**Issue by Przylepzwm** [normen/homebridge-landroid#47]
Everything worked fine for a year. Now when restarting homebridge I have this info as below. Does anyone know what the cause could be?

[22/11/2022, 19:52:21] ====================
[22/11/2022, 19:52:21] ERROR LOADING PLUGIN homebridge-landroid:
[22/11/2022, 19:52:21] Error: Cannot find module 'node:url'

  Require stack:
  - /usr/local/lib/node_modules/homebridge-landroid/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js
  - /usr/local/lib/node_modules/homebridge-landroid/node_modules/http-cookie-agent/dist/http/index.js
  - /usr/local/lib/node_modules/homebridge-landroid/node_modules/http-cookie-agent/http/index.js
  - /usr/local/lib/node_modules/homebridge-landroid/node_modules/iobroker.worx/lib/api.js
  - /usr/local/lib/node_modules/homebridge-landroid/index.js
  - /usr/local/lib/node_modules/homebridge/lib/plugin.js
  - /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
  - /usr/local/lib/node_modules/homebridge/lib/server.js
  - /usr/local/lib/node_modules/homebridge/lib/cli.js
  - /usr/local/lib/node_modules/homebridge/bin/homebridge
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
      at Function.Module._load (internal/modules/cjs/loader.js:746:27)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:92:18)
      at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-landroid/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:8:39)
      at Module._compile (internal/modules/cjs/loader.js:1085:14)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
      at Module.load (internal/modules/cjs/loader.js:950:32)
      at Function.Module._load (internal/modules/cjs/loader.js:790:14)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:92:18)
      at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-landroid/node_modules/http-cookie-agent/dist/http/index.js:37:28)
      at Module._compile (internal/modules/cjs/loader.js:1085:14)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
      at Module.load (internal/modules/cjs/loader.js:950:32)
      at Function.Module._load (internal/modules/cjs/loader.js:790:14)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:92:18)
      at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-landroid/node_modules/http-cookie-agent/http/index.js:1:18)
      at Module._compile (internal/modules/cjs/loader.js:1085:14)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
      at Module.load (internal/modules/cjs/loader.js:950:32)

[22/11/2022, 19:52:21] ====================

**Comment by normen** [comment]
Apart from the fact that the plugin currently doesn't work this error is something different. What version of Node are you running your homebridge on?

**Comment by Przylepzwm** [comment]
@normen  v14.17.1

There is another log during the reboot:
[22/11/2022, 19:52:26] No plugin was found for the platform "Landroid" in your config.json. Please make sure the corresponding plugin is installed correctly.

*Landroid is added in the configuration file (worked before)

**Comment by normen** [comment]
Wow, thats ancient. Homebridge itself requires at least Node 16 by now. I guess thats the core issue here. The latter error is due to the first. That is the plugin can't be loaded hence it can't be found.

**Comment by Przylepzwm** [comment]
Will try to do an update and let you know if the problem has disappeared

**Comment by normen** [comment]
As said the plugin currently isn't working properly anyway as the login method changed, still it should not crash like that.

**Comment by jbuttnz** [comment]
Please advise once updated.

**Comment by normen** [comment]
Please test now that its updated.

**Comment by Przylepzwm** [comment]
Now its works!

**Comment by jbuttnz** [comment]
Yes! working perfectly. Thank you :)
