### ISSUE TITLE
Error while updating 0.11.5 => 0.11.9 / No update or deleting possible

### ISSUE THREAD

**Issue by Madcat-76310** [normen/homebridge-landroid#59]
Hi,
I've tried to update the plugin from 0.11.5 to 0.11.9, but i've an error message (see below). Since this trial, i can't delete the plugin with the same type of error (see second message)...

Running post-install scripts...
/opt/homebridge/lib/node_modules/npm/lib/cli.js:48
    throw err
    ^

Error: Cannot find module 'semver/functions/satisfies'
Require stack:
- /opt/homebridge/lib/node_modules/npm/lib/cli.js
- /opt/homebridge/lib/node_modules/npm/bin/npm-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at module.exports (/opt/homebridge/lib/node_modules/npm/lib/cli.js:80:21)
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/homebridge/lib/node_modules/npm/lib/cli.js',
    '/opt/homebridge/lib/node_modules/npm/bin/npm-cli.js'
  ]
}

Node.js v18.16.1
Failed to rebuild.
Restoring previous version...
Restore Complete. Installation failed.

Bundled install / update could not complete. Trying regular install / update using npm.

USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-landroid@0.11.9

/opt/homebridge/lib/node_modules/npm/lib/cli.js:48
    throw err
    ^

Error: Cannot find module 'semver/functions/satisfies'
Require stack:
- /opt/homebridge/lib/node_modules/npm/lib/cli.js
- /opt/homebridge/lib/node_modules/npm/bin/npm-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at module.exports (/opt/homebridge/lib/node_modules/npm/lib/cli.js:80:21)
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/homebridge/lib/node_modules/npm/lib/cli.js',
    '/opt/homebridge/lib/node_modules/npm/bin/npm-cli.js'
  ]
}

Node.js v18.16.1

Operation failed. Please review log for details.

**Comment by Madcat-76310** [comment]
I can't delete the plugin in home bridge with this error message : 

USER: homebridge
DIR: /var/lib/homebridge
CMD: npm uninstall --save homebridge-landroid

/opt/homebridge/lib/node_modules/npm/lib/cli.js:48
    throw err
    ^

Error: Cannot find module 'semver/functions/satisfies'
Require stack:
- /opt/homebridge/lib/node_modules/npm/lib/cli.js
- /opt/homebridge/lib/node_modules/npm/bin/npm-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at module.exports (/opt/homebridge/lib/node_modules/npm/lib/cli.js:80:21)
    at Object.<anonymous> (/opt/homebridge/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/homebridge/lib/node_modules/npm/lib/cli.js',
    '/opt/homebridge/lib/node_modules/npm/bin/npm-cli.js'
  ]
}

Node.js v18.16.1

Operation failed. Please review log for details.

**Comment by normen** [comment]
Your node.js installation is borked.

**Comment by Madcat-76310** [comment]
Yes, I didn't understand why... Problem solved after deleting two files and making the update :

/opt/homebridge/lib/node_modules/npm/lib/cli.js
/opt/homebridge/lib/node_modules/npm/bin/npm-cli.js
