### ISSUE TITLE
Homebridge v2.0

### ISSUE THREAD

**Issue by wesker84** [normen/homebridge-landroid#67]
Hi, I just want to inform that plugin seems not to be ready for new Homebridge version 2.0 yet, that will be released soon: 

Log:
```
TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
    at new LandroidAccessory (/var/lib/homebridge/node_modules/homebridge-landroid/index.js:206:54)
    at LandroidPlatform.configureAccessory (/var/lib/homebridge/node_modules/homebridge-landroid/index.js:107:25)
    at /var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:317:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:279:69)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:176:24)
```

As far as I understand as a non-coder, solution may be quite simple (I hope so), see developer information here: 
https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

Would be happy if a solution could be found. Thanks :)

**Comment by wesker84** [comment]
Sorry, have not seen "discontinued"-message before...
