### ISSUE TITLE
Homebridge shutdown 

### ISSUE THREAD

**Issue by CharlieSierra81** [normen/homebridge-landroid#8]
Hello, 
I was using the plugin for several weeks on a Synology NAS running docker without any issues. Since last DSM update plugin forces homebridge to shut down. Any ideas?
Log extract:
37m[6/13/2019, 2:01:14 AM][39m [1m[31mSyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-landroid/node_modules/iobroker.landroid-s/lib/mqttCloud.js:275:21)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by normen** [comment]
Update the plugin?
